apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 3
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: log-output-data
          emptyDir: {}
      containers:
        - name: writer
          image: PROJECT/IMAGE
          command: ["node", "reader-writer.js", "writer"]
          volumeMounts:
            - name: log-output-data
              mountPath: /data
        - name: reader
          image: PROJECT/IMAGE
          command: ["node", "reader-writer.js", "reader"]
          volumeMounts:
            - name: log-output-data
              mountPath: /data
          ports:
            - containerPort: 3000
